server:
     port: 8081
spring:
     application:
         name: user-service
     datasource:
         url: jdbc:postgresql://localhost:5432/mackerelpike
         username: postgres
         password: 123456
         driver-class-nam: org.postgresql.Driver
mybatis:
      config-locations: classpath:mybatis/mybatis-config.xml
      mapper-locations: classpath:mybatis/mapper/*.xml
      type-aliases-package: com.mackerelpike.springcloud.user_service.po